[13/Apr/2018 11:37:34]"GET /admin/login/?next=/admin/ HTTP/1.1" 200 1915
[13/Apr/2018 11:37:34]"GET /static/admin/css/base.css HTTP/1.1" 304 0
[13/Apr/2018 11:37:34]"GET /static/admin/css/login.css HTTP/1.1" 304 0
[13/Apr/2018 11:37:34]"GET /static/admin/img/nav-bg.gif HTTP/1.1" 304 0
[13/Apr/2018 11:37:39]"GET /admin/login/?next=/admin/ HTTP/1.1" 200 1915
[13/Apr/2018 11:37:42]"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[13/Apr/2018 11:37:42]"GET /admin/ HTTP/1.1" 200 3018
[13/Apr/2018 11:37:42]"GET /static/admin/css/dashboard.css HTTP/1.1" 200 434
[13/Apr/2018 11:37:42]"GET /static/admin/img/default-bg.gif HTTP/1.1" 200 836
[13/Apr/2018 11:37:42]"GET /static/admin/img/icon_addlink.gif HTTP/1.1" 200 119
[13/Apr/2018 11:37:42]"GET /static/admin/img/icon_changelink.gif HTTP/1.1" 200 119
/home/wfq/python27/lib/python2.7/site-packages/celery-3.1.25-py2.7.egg/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))

[2018-06-28 10:12:55,129: WARNING/MainProcess] /home/wfq/python27/lib/python2.7/site-packages/celery-3.1.25-py2.7.egg/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.


  warnings.warn(CDeprecationWarning(W_PICKLE_DEPRECATED))

[2018-06-28 10:12:56,094: ERROR/MainProcess] consumer: Cannot connect to redis://192.168.174.132:6379/0: .
Trying again in 2.00 seconds...

[2018-06-28 10:12:58,149: ERROR/MainProcess] consumer: Cannot connect to redis://192.168.174.132:6379/0: .
Trying again in 4.00 seconds...

[2018-06-28 10:13:02,183: ERROR/MainProcess] consumer: Cannot connect to redis://192.168.174.132:6379/0: .
Trying again in 6.00 seconds...

[2018-06-28 10:13:08,194: ERROR/MainProcess] consumer: Cannot connect to redis://192.168.174.132:6379/0: .
Trying again in 8.00 seconds...

[2018-06-28 10:13:16,204: ERROR/MainProcess] consumer: Cannot connect to redis://192.168.174.132:6379/0: .
Trying again in 10.00 seconds...

[2018-06-28 10:13:26,216: ERROR/MainProcess] consumer: Cannot connect to redis://192.168.174.132:6379/0: .
Trying again in 12.00 seconds...

[2018-06-28 10:13:38,237: ERROR/MainProcess] consumer: Cannot connect to redis://192.168.174.132:6379/0: .
Trying again in 14.00 seconds...

[2018-06-28 10:13:52,265: ERROR/MainProcess] consumer: Cannot connect to redis://192.168.174.132:6379/0: .
Trying again in 16.00 seconds...

[2018-06-28 10:14:08,288: ERROR/MainProcess] consumer: Cannot connect to redis://192.168.174.132:6379/0: .
Trying again in 18.00 seconds...

[2018-06-28 10:14:26,312: ERROR/MainProcess] consumer: Cannot connect to redis://192.168.174.132:6379/0: .
Trying again in 20.00 seconds...

[2018-06-28 10:14:46,340: ERROR/MainProcess] consumer: Cannot connect to redis://192.168.174.132:6379/0: .
Trying again in 22.00 seconds...

[2018-06-28 10:15:08,367: ERROR/MainProcess] consumer: Cannot connect to redis://192.168.174.132:6379/0: .
Trying again in 24.00 seconds...

[2018-06-28 10:15:32,396: ERROR/MainProcess] consumer: Cannot connect to redis://192.168.174.132:6379/0: .
Trying again in 26.00 seconds...

[2018-06-28 10:15:58,443: ERROR/MainProcess] consumer: Cannot connect to redis://192.168.174.132:6379/0: .
Trying again in 28.00 seconds...

[2018-06-28 10:16:26,482: ERROR/MainProcess] consumer: Cannot connect to redis://192.168.174.132:6379/0: .
Trying again in 30.00 seconds...

[2018-06-28 10:16:56,521: ERROR/MainProcess] consumer: Cannot connect to redis://192.168.174.132:6379/0: .
Trying again in 32.00 seconds...

[2018-06-28 10:17:28,566: ERROR/MainProcess] consumer: Cannot connect to redis://192.168.174.132:6379/0: .
Trying again in 32.00 seconds...

[2018-06-28 10:18:00,607: ERROR/MainProcess] consumer: Cannot connect to redis://192.168.174.132:6379/0: .
Trying again in 32.00 seconds...

